services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  node:
    build:
      context: ./server
    container_name: node
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/library-db

  angular:
    build:
      context: ./client
    container_name: angular
    ports:
      - "80:80"

volumes:
  mongodb_data:
